// Generated by Selenium IDE

import org.openqa.selenium.firefox.FirefoxDriver;

import io.github.bonigarcia.seljup.SeleniumJupiter;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@ExtendWith(SeleniumJupiter.class)
public class TestTravel{

  @Test
  public void Teste(FirefoxDriver driver) throws InterruptedException {
    
    HomePage homePage = new HomePage(driver);

    homePage.selectFromPort("Portland");
    homePage.selectToPort("Berlin");
    homePage.clickConfirm();

    ReservePage reservePage = new ReservePage(driver);

    assertThat(reservePage.assertInPage());
    reservePage.goToNextPage();

    PurchasePage purchasePage = new PurchasePage(driver);
    
    assertThat(purchasePage.inPage());
    purchasePage.nextPageClick();
    
    ConfirmationPage confirmationPage = new ConfirmationPage(driver);
    assertThat(confirmationPage.assertInPage());

    Thread.sleep(2000);
  }
}
